-- Markdown buffer-local tweaks. Loaded automatically on FileType=markdown.

-- Spellcheck (en + pt for prose, programming for jargon, custom for words
-- missing from the others) and line wrap. The Vim spell repo only ships
-- `pt.utf-8.spl` (no `pt_br` variant); it still catches Brazilian Portuguese
-- fine. The `programming` dict is generated by vim-dirtytalk
-- (`:DirtytalkUpdate`), and `custom` from `~/.config/nvim/spell/custom.words`
-- (`:CustomSpellUpdate`).
vim.opt_local.spell = true
vim.opt_local.spelllang = { "en", "pt", "programming", "custom" }
vim.opt_local.wrap = true
-- Slugs like `mini-files` should count as a single word for `w`/`*`/spell.
vim.opt_local.iskeyword:append("-")
-- `linebreak` keeps wrap from breaking mid-word; `breakindent` makes wrapped
-- lines pick up the surrounding indent, which keeps lists and quoted blocks
-- visually aligned in long-form writing.
vim.opt_local.linebreak = true
vim.opt_local.breakindent = true
vim.opt_local.breakindentopt = "shift:2,min:40"

-- `spellfile` is the list of personal `.add` files that `zg`/`zw` write to.
-- The numeric prefix selects the entry (1zg=en, 2zg=pt, 3zg=programming,
-- 4zg=custom). Order must mirror `spelllang` above. Each `.add` is auto-
-- compiled by Vim into `<name>.add.spl` next to it on save.
local spell_add = vim.fn.stdpath("config") .. "/spell"
vim.opt_local.spellfile = {
    spell_add .. "/en.utf-8.add",
    spell_add .. "/pt.utf-8.add",
    spell_add .. "/programming.utf-8.add",
    spell_add .. "/custom.utf-8.add",
}

-- Use tree-sitter for folds (headers `#`, `##`, ... become foldable sections).
-- Overrides the global `foldmethod = indent`, which is meaningless in markdown.
vim.cmd("setlocal foldmethod=expr foldexpr=v:lua.vim.treesitter.foldexpr()")

-- Custom mini.surround target for markdown links. Usage:
--   `saiwL` + [type link] + <CR>   add `[word](link)` around inner word
--   `sdL`                          unwrap the link (keep only the visible text)
--   `srLL` + [type link] + <CR>    replace the link target
vim.b.minisurround_config = {
    custom_surroundings = {
        L = {
            input = { "%[().-()%]%(.-%)" },
            output = function()
                local link = require("mini.surround").user_input("Link: ")
                return { left = "[", right = "](" .. link .. ")" }
            end,
        },
    },
}
